# Generated by Django 2.2.3 on 2019-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='example_app.Author'),
        ),
    ]
