# Generated by Django 2.2.3 on 2019-10-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0005_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
