# SETTINGS CONFIG KEYS
SETTINGS_CONFIG = 'PNP_GRAPHQL'
SETTINGS_ENABLED_APPS = 'ENABLED_APPS'
SETTINGS_AUTH_CLASS = 'AUTHENTICATION_CLASS'

# Model Attribute constants
MODEL_TYPE_ATTR = 'pnp_gql_type'
MODEL_INPUT_ATTR = 'pnp_gql_input'
