# Generated by Django 2.2.3 on 2019-08-14 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnp_graphql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authtoken', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
